name: incubator-seata

on:
  push:
    paths:
      - .github/workflows/incubator-seata.yml
  workflow_dispatch:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://dist.apache.org/repos/dist/dev/incubator/seata
      VERSION: 2.7.0
    steps:
      - name: Download release artifacts
        run: |
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.asc
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-src.zip
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-src.zip.asc
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-src.zip.sha512
      - name: List downloaded files
        run: ls -lha
      - name: Verify SHA-512 checksums
        run: |
          sha512sum -c apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
          sha512sum -c apache-seata-${{ env.VERSION }}-incubating-src.zip.sha512
