name: incubator-seata

on:
  push:
    paths:
      - .github/workflows/incubator-seata.yml
  workflow_dispatch:
    inputs:
      version:
        description: 'Seata version to verify'
        required: true
        default: '2.7.0'
        type: string

env:
  BASE_URL: https://dist.apache.org/repos/dist/dev/incubator/seata
  KEYS_URL: https://downloads.apache.org/incubator/seata/KEYS
  VERSION: ${{ github.event.inputs.version || '2.7.0' }}

jobs:
  check-license-server:
    name: check-license-server
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts (binary)
        run: |
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.asc
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
      - name: List downloaded files
        run: ls -lha
      - name: Verify SHA-512 checksums
        run: |
          sha512sum -c apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
      - name: Import GPG KEYS
        run: |
          curl -LO ${{ env.KEYS_URL }}
          gpg --import KEYS
      - name: Verify GPG signatures
        run: |
          gpg --verify apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.asc apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
      - name: Extract binary tarball
        run: tar -zxvf apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
      - name: Display seata-server LICENSE
        run: cat apache-seata-${{ env.VERSION }}-incubating-bin/seata-server/LICENSE

  check-license-namingserver:
    name: check-license-namingserver
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts (binary)
        run: |
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.asc
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
      - name: List downloaded files
        run: ls -lha
      - name: Verify SHA-512 checksums
        run: |
          sha512sum -c apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
      - name: Import GPG KEYS
        run: |
          curl -LO ${{ env.KEYS_URL }}
          gpg --import KEYS
      - name: Verify GPG signatures
        run: |
          gpg --verify apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.asc apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
      - name: Extract binary tarball
        run: tar -zxvf apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
      - name: Display seata-namingserver LICENSE
        run: cat apache-seata-${{ env.VERSION }}-incubating-bin/seata-namingserver/LICENSE

  check-notice-server:
    name: check-notice-server
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts (binary)
        run: |
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.asc
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
      - name: List downloaded files
        run: ls -lha
      - name: Verify SHA-512 checksums
        run: |
          sha512sum -c apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
      - name: Import GPG KEYS
        run: |
          curl -LO ${{ env.KEYS_URL }}
          gpg --import KEYS
      - name: Verify GPG signatures
        run: |
          gpg --verify apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.asc apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
      - name: Extract binary tarball
        run: tar -zxvf apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
      - name: Display seata-server NOTICE
        run: cat apache-seata-${{ env.VERSION }}-incubating-bin/seata-server/NOTICE
      - name: Check seata-server NOTICE first line
        run: |
          FIRST_LINE=$(head -n 1 apache-seata-${{ env.VERSION }}-incubating-bin/seata-server/NOTICE)
          EXPECTED="Apache Seata (Incubating)"
          if [ "$FIRST_LINE" != "$EXPECTED" ]; then
            echo "ERROR: Expected first line of seata-server/NOTICE to be '$EXPECTED', but got '$FIRST_LINE'"
            exit 1
          fi
          echo "OK: seata-server/NOTICE first line is '$FIRST_LINE'"
      - name: Check seata-server NOTICE second line
        run: |
          SECOND_LINE=$(head -n 2 apache-seata-${{ env.VERSION }}-incubating-bin/seata-server/NOTICE | tail -n 1)
          CURRENT_YEAR=$(date +%Y)
          echo "CURRENT_YEAR=$CURRENT_YEAR"
          EXPECTED="Copyright 2023-${CURRENT_YEAR} The Apache Software Foundation"
          if [ "$SECOND_LINE" != "$EXPECTED" ]; then
            echo "ERROR: Expected second line of seata-server/NOTICE to be '$EXPECTED', but got '$SECOND_LINE'"
            exit 1
          fi
          echo "OK: seata-server/NOTICE second line is '$SECOND_LINE'"

  check-notice-namingserver:
    name: check-notice-namingserver
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts (binary)
        run: |
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.asc
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
      - name: List downloaded files
        run: ls -lha
      - name: Verify SHA-512 checksums
        run: |
          sha512sum -c apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.sha512
      - name: Import GPG KEYS
        run: |
          curl -LO ${{ env.KEYS_URL }}
          gpg --import KEYS
      - name: Verify GPG signatures
        run: |
          gpg --verify apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz.asc apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
      - name: Extract binary tarball
        run: tar -zxvf apache-seata-${{ env.VERSION }}-incubating-bin.tar.gz
      - name: Display seata-namingserver NOTICE
        run: cat apache-seata-${{ env.VERSION }}-incubating-bin/seata-namingserver/NOTICE
      - name: Check seata-namingserver NOTICE first line
        run: |
          FIRST_LINE=$(head -n 1 apache-seata-${{ env.VERSION }}-incubating-bin/seata-namingserver/NOTICE)
          EXPECTED="Apache Seata (Incubating)"
          if [ "$FIRST_LINE" != "$EXPECTED" ]; then
            echo "ERROR: Expected first line of seata-namingserver/NOTICE to be '$EXPECTED', but got '$FIRST_LINE'"
            exit 1
          fi
          echo "OK: seata-namingserver/NOTICE first line is '$FIRST_LINE'"
      - name: Check seata-namingserver NOTICE second line
        run: |
          SECOND_LINE=$(head -n 2 apache-seata-${{ env.VERSION }}-incubating-bin/seata-namingserver/NOTICE | tail -n 1)
          CURRENT_YEAR=$(date +%Y)
          echo "CURRENT_YEAR=$CURRENT_YEAR"
          EXPECTED="Copyright 2023-${CURRENT_YEAR} The Apache Software Foundation"
          if [ "$SECOND_LINE" != "$EXPECTED" ]; then
            echo "ERROR: Expected second line of seata-namingserver/NOTICE to be '$EXPECTED', but got '$SECOND_LINE'"
            exit 1
          fi
          echo "OK: seata-namingserver/NOTICE second line is '$SECOND_LINE'"

  check-zip-compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 17, 21, 25 ]
    steps:
      - name: Download release artifacts
        run: |
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-src.zip
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-src.zip.asc
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-src.zip.sha512
      - name: List downloaded files
        run: ls -lha
      - name: Verify SHA-512 checksums
        run: |
          sha512sum -c apache-seata-${{ env.VERSION }}-incubating-src.zip.sha512
      - name: Import GPG KEYS
        run: |
          curl -LO ${{ env.KEYS_URL }}
          gpg --import KEYS
      - name: Verify GPG signatures
        run: |
          gpg --verify apache-seata-${{ env.VERSION }}-incubating-src.zip.asc apache-seata-${{ env.VERSION }}-incubating-src.zip
      - name: Extract source zip
        run: unzip apache-seata-${{ env.VERSION }}-incubating-src.zip
      - name: "Setup Java JDK"
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Compile with Maven
        working-directory: apache-seata-${{ env.VERSION }}-incubating-src
        run: ./mvnw -V -B clean package -DskipTests=true

  check-zip-license:
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts
        run: |
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-src.zip
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-src.zip.asc
          curl -LO ${{ env.BASE_URL }}/${{ env.VERSION }}/apache-seata-${{ env.VERSION }}-incubating-src.zip.sha512
      - name: List downloaded files
        run: ls -lha
      - name: Verify SHA-512 checksums
        run: |
          sha512sum -c apache-seata-${{ env.VERSION }}-incubating-src.zip.sha512
      - name: Import GPG KEYS
        run: |
          curl -LO ${{ env.KEYS_URL }}
          gpg --import KEYS
      - name: Verify GPG signatures
        run: |
          gpg --verify apache-seata-${{ env.VERSION }}-incubating-src.zip.asc apache-seata-${{ env.VERSION }}-incubating-src.zip
      - name: Extract source zip
        run: unzip apache-seata-${{ env.VERSION }}-incubating-src.zip
      - name: List extracted source files
        run: ls -lha
      - name: Move extracted source files to current directory
        run: shopt -s dotglob && mv apache-seata-${{ env.VERSION }}-incubating-src/* . && shopt -u dotglob
      - name: Remove non-compliant license files
        run: |
          rm -rf apache-seata-${{ env.VERSION }}-incubating-src.zip
          rm -rf apache-seata-${{ env.VERSION }}-incubating-src.zip.asc
          rm -rf apache-seata-${{ env.VERSION }}-incubating-src.zip.sha512
          rm -rf KEYS
      - name: Clear cache directory first before trying to restore from cache
        run: sudo rm -rf $(go env GOMODCACHE) && sudo rm -rf $(go env GOCACHE)
        shell: bash
      # https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Check License Header
        uses: apache/skywalking-eyes/header@8fc52baabc14c86294d96034bcc194cfa7f76b05
        with:
          log: info
          config: .licenserc.yaml
          mode: check
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@8fc52baabc14c86294d96034bcc194cfa7f76b05
        with:
          log: info
          config: .licenserc.yaml
          mode: check

  check-tag-compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 17, 21, 25 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: apache/incubator-seata
          ref: ${{ env.VERSION }}
      - name: "Setup Java JDK"
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Compile with Maven
        run: ./mvnw -V -B clean package -DskipTests=true

  check-tag-license:
    runs-on: ubuntu-latest
    steps:
      # step 1 clear cache
      - name: Clear cache directory first before trying to restore from cache
        run: sudo rm -rf $(go env GOMODCACHE) && sudo rm -rf $(go env GOCACHE)
        shell: bash
      # step 2 checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: apache/incubator-seata
          ref: ${{ env.VERSION }}
      # step 3 https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      # step 4 check license
      - name: Check License Header
        uses: apache/skywalking-eyes/header@8fc52baabc14c86294d96034bcc194cfa7f76b05
        with:
          log: info
          config: .licenserc.yaml
          mode: check
      # step 5 check dependencies
      - name: Check Dependencies' License
        uses: apache/skywalking-eyes/dependency@8fc52baabc14c86294d96034bcc194cfa7f76b05
        with:
          log: info
          config: .licenserc.yaml
          mode: check
